<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Shravani Jadhav">

<title>Australian Election Trends Analysis (2022–2025)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="australian_election_analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="australian_election_analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="australian_election_analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="australian_election_analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="australian_election_analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="australian_election_analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="australian_election_analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="australian_election_analysis_files/libs/quarto-html/quarto-syntax-highlighting-7c69b197886ae2a34062761d21e44731.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="australian_election_analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="australian_election_analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="australian_election_analysis_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview"><strong>Overview</strong></a></li>
  <li><a href="#fact-checker" id="toc-fact-checker" class="nav-link" data-scroll-target="#fact-checker"><strong>Fact checker</strong></a></li>
  <li><a href="#spatial-analysis" id="toc-spatial-analysis" class="nav-link" data-scroll-target="#spatial-analysis"><strong>Spatial analysis</strong></a></li>
  <li><a href="#demographic-deep-dive" id="toc-demographic-deep-dive" class="nav-link" data-scroll-target="#demographic-deep-dive"><strong>Demographic deep dive</strong></a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings"><strong>Key Findings</strong></a>
  <ul class="collapse">
  <li><a href="#fact-checker-method-and-results" id="toc-fact-checker-method-and-results" class="nav-link" data-scroll-target="#fact-checker-method-and-results"><strong>Fact Checker method and results</strong></a></li>
  <li><a href="#method" id="toc-method" class="nav-link" data-scroll-target="#method">Method:</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results:</a></li>
  <li><a href="#spatial-analysis-method-and-results" id="toc-spatial-analysis-method-and-results" class="nav-link" data-scroll-target="#spatial-analysis-method-and-results"><strong>Spatial Analysis method and results</strong></a></li>
  <li><a href="#method-1" id="toc-method-1" class="nav-link" data-scroll-target="#method-1">Method</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#demographic-deep-dive-and-results" id="toc-demographic-deep-dive-and-results" class="nav-link" data-scroll-target="#demographic-deep-dive-and-results"><strong>Demographic Deep Dive and Results</strong></a></li>
  <li><a href="#census-variables--" id="toc-census-variables--" class="nav-link" data-scroll-target="#census-variables--">Census Variables -</a></li>
  <li><a href="#spatial-join-method--" id="toc-spatial-join-method--" class="nav-link" data-scroll-target="#spatial-join-method--">Spatial Join Method -</a></li>
  <li><a href="#quality-checks-and-limitations--" id="toc-quality-checks-and-limitations--" class="nav-link" data-scroll-target="#quality-checks-and-limitations--">Quality Checks and Limitations -</a></li>
  <li><a href="#results--" id="toc-results--" class="nav-link" data-scroll-target="#results--">Results -</a></li>
  </ul></li>
  <li><a href="#citations" id="toc-citations" class="nav-link" data-scroll-target="#citations"><strong>CITATIONS</strong></a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="australian_election_analysis.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Australian Election Trends Analysis (2022–2025)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Shravani Jadhav </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1><strong>Overview</strong></h1>
<p>This project investigates the shift in Australian federal election voting patterns between 2022 and 2025, following the reported change where minor parties and independents collectively received more first preference votes than the Liberal–National Coalition in the 2025 federal election. The analysis examines whether this national voting shift is reflected across individual electorates and explores the demographic characteristics of electorates experiencing strong changes in voter preferences.</p>
</section>
<section id="fact-checker" class="level1">
<h1><strong>Fact checker</strong></h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load and combine the data</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in 2022 data, skipping the first row</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>data_2022 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/HouseDopByDivisionDownload-27966_2022.csv"</span>, </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>                      <span class="at">skip =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="dv">2022</span>)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in 2025 data</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>data_2025 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/HouseDopByDivisionDownload-31496_2025.csv"</span>, </span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>                      <span class="at">skip =</span> <span class="dv">1</span>) <span class="sc">|&gt;</span> </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="dv">2025</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine into one data frame</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>data_combined <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(data_2022, data_2025)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Check it looks right</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data_combined)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 65,984
Columns: 15
$ StateAb          &lt;chr&gt; "ACT", "ACT", "ACT", "ACT", "ACT", "ACT", "ACT", "ACT…
$ DivisionID       &lt;dbl&gt; 318, 318, 318, 318, 318, 318, 318, 318, 318, 318, 318…
$ DivisionNm       &lt;chr&gt; "Bean", "Bean", "Bean", "Bean", "Bean", "Bean", "Bean…
$ CountNumber      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ BallotPosition   &lt;dbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,…
$ CandidateID      &lt;dbl&gt; 36239, 36239, 36239, 36239, 37455, 37455, 37455, 3745…
$ Surname          &lt;chr&gt; "CONWAY", "CONWAY", "CONWAY", "CONWAY", "AMBARD", "AM…
$ GivenNm          &lt;chr&gt; "Sean", "Sean", "Sean", "Sean", "Benjamin", "Benjamin…
$ PartyAb          &lt;chr&gt; "UAPP", "UAPP", "UAPP", "UAPP", "ON", "ON", "ON", "ON…
$ PartyNm          &lt;chr&gt; "United Australia Party", "United Australia Party", "…
$ Elected          &lt;chr&gt; "N", "N", "N", "N", "N", "N", "N", "N", "Y", "Y", "Y"…
$ HistoricElected  &lt;chr&gt; "N", "N", "N", "N", "N", "N", "N", "N", "Y", "Y", "Y"…
$ CalculationType  &lt;chr&gt; "Preference Count", "Preference Percent", "Transfer C…
$ CalculationValue &lt;dbl&gt; 2831.00, 2.88, 0.00, 0.00, 2680.00, 2.72, 0.00, 0.00,…
$ year             &lt;dbl&gt; 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022, 2022,…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># See all unique parties</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>data_combined <span class="sc">|&gt;</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(PartyAb, PartyNm) <span class="sc">|&gt;</span> </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(PartyAb) <span class="sc">|&gt;</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 55 × 2
   PartyAb PartyNm                                                        
   &lt;chr&gt;   &lt;chr&gt;                                                          
 1 AJP     Animal Justice Party                                           
 2 AJP     AJP                                                            
 3 ALP     Australian Labor Party                                         
 4 ALP     Labor                                                          
 5 ALP     A.L.P.                                                         
 6 ALP     Australian Labor Party (Northern Territory) Branch             
 7 ASP     Shooters, Fishers and Farmers Party                            
 8 AUC     Australian Christians                                          
 9 AUD     Australian Democrats                                           
10 AUP     Australian Progressives                                        
11 AUVA    Australian Values Party                                        
12 CEC     Citizens Party                                                 
13 CLP     NT CLP                                                         
14 CYA     Australian Federation Party                                    
15 CYA     Trumpet of Patriots                                            
16 DHJP    Derryn Hinch's Justice Party                                   
17 DPDA    Democratic Alliance                                            
18 DPDA    Drew Pavlou Democratic Alliance                                
19 FFPA    Family First                                                   
20 GAP     The Great Australian Party                                     
21 GRN     The Greens                                                     
22 GRN     Queensland Greens                                              
23 GRN     The Greens (WA)                                                
24 GRN     Australian Greens                                              
25 GRN     The Greens (WA) Inc                                            
26 GRPF    Gerard Rennick People First                                    
27 GVIC    The Greens                                                     
28 HMP     Legalise Cannabis Australia                                    
29 HMP     Legalise Cannabis Party                                        
30 IAP     Indigenous - Aboriginal Party of Australia                     
31 IMO     Informed Medical Options Party                                 
32 IMO     HEART Party                                                    
33 IND     Independent                                                    
34 JLN     Jacqui Lambie Network                                          
35 KAP     Katter's Australian Party (KAP)                                
36 LDP     Liberal Democrats                                              
37 LNP     Liberal National Party of Queensland                           
38 LNP     LNP                                                            
39 LP      Liberal                                                        
40 LTP     Libertarian                                                    
41 NP      The Nationals                                                  
42 NP      National Party                                                 
43 ON      Pauline Hanson's One Nation                                    
44 REAS    Reason Australia                                               
45 SAL     Socialist Alliance                                             
46 SOPA    FUSION: Science, Pirate, Secular, Climate Emergency            
47 SOPA    FUSION | Planet Rescue | Whistleblower Protection | Innovation 
48 SPP     Sustainable Australia Party - Stop Overdevelopment / Corruption
49 TLOC    The Local Party                                                
50 TNL     TNL                                                            
51 UAPP    United Australia Party                                         
52 VNS     Victorian Socialists                                           
53 WAP     WESTERN AUSTRALIA PARTY                                        
54 XEN     Centre Alliance                                                
55 &lt;NA&gt;    &lt;NA&gt;                                                           </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Classify parties into groups</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>data_classified <span class="ot">&lt;-</span> data_combined <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">PartyType =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      PartyAb <span class="sc">==</span> <span class="st">"ALP"</span> <span class="sc">~</span> <span class="st">"major_labour"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      PartyAb <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"LP"</span>, <span class="st">"NP"</span>, <span class="st">"LNP"</span>, <span class="st">"CLP"</span>) <span class="sc">~</span> <span class="st">"major_coal"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"minor_or_indep"</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the classification looks right</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>data_classified <span class="sc">|&gt;</span> </span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(PartyAb, PartyNm, PartyType) <span class="sc">|&gt;</span> </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(PartyType) <span class="sc">|&gt;</span> </span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">100</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 55 × 3
   PartyAb PartyNm                                                     PartyType
   &lt;chr&gt;   &lt;chr&gt;                                                       &lt;chr&gt;    
 1 LP      Liberal                                                     major_co…
 2 NP      The Nationals                                               major_co…
 3 CLP     NT CLP                                                      major_co…
 4 LNP     Liberal National Party of Queensland                        major_co…
 5 NP      National Party                                              major_co…
 6 LNP     LNP                                                         major_co…
 7 ALP     Australian Labor Party                                      major_la…
 8 ALP     Labor                                                       major_la…
 9 ALP     A.L.P.                                                      major_la…
10 ALP     Australian Labor Party (Northern Territory) Branch          major_la…
11 UAPP    United Australia Party                                      minor_or…
12 ON      Pauline Hanson's One Nation                                 minor_or…
13 IND     Independent                                                 minor_or…
14 GRN     The Greens                                                  minor_or…
15 LDP     Liberal Democrats                                           minor_or…
16 &lt;NA&gt;    &lt;NA&gt;                                                        minor_or…
17 SOPA    FUSION: Science, Pirate, Secular, Climate Emergency         minor_or…
18 DPDA    Democratic Alliance                                         minor_or…
19 CYA     Australian Federation Party                                 minor_or…
20 CEC     Citizens Party                                              minor_or…
21 SPP     Sustainable Australia Party - Stop Overdevelopment / Corru… minor_or…
22 AUD     Australian Democrats                                        minor_or…
23 IMO     Informed Medical Options Party                              minor_or…
24 ASP     Shooters, Fishers and Farmers Party                         minor_or…
25 AJP     Animal Justice Party                                        minor_or…
26 TNL     TNL                                                         minor_or…
27 IAP     Indigenous - Aboriginal Party of Australia                  minor_or…
28 SAL     Socialist Alliance                                          minor_or…
29 GRN     Queensland Greens                                           minor_or…
30 AUVA    Australian Values Party                                     minor_or…
31 GAP     The Great Australian Party                                  minor_or…
32 KAP     Katter's Australian Party (KAP)                             minor_or…
33 HMP     Legalise Cannabis Australia                                 minor_or…
34 AUP     Australian Progressives                                     minor_or…
35 XEN     Centre Alliance                                             minor_or…
36 DPDA    Drew Pavlou Democratic Alliance                             minor_or…
37 JLN     Jacqui Lambie Network                                       minor_or…
38 TLOC    The Local Party                                             minor_or…
39 GVIC    The Greens                                                  minor_or…
40 VNS     Victorian Socialists                                        minor_or…
41 DHJP    Derryn Hinch's Justice Party                                minor_or…
42 REAS    Reason Australia                                            minor_or…
43 GRN     The Greens (WA)                                             minor_or…
44 AUC     Australian Christians                                       minor_or…
45 WAP     WESTERN AUSTRALIA PARTY                                     minor_or…
46 GRN     Australian Greens                                           minor_or…
47 IMO     HEART Party                                                 minor_or…
48 AJP     AJP                                                         minor_or…
49 FFPA    Family First                                                minor_or…
50 CYA     Trumpet of Patriots                                         minor_or…
51 LTP     Libertarian                                                 minor_or…
52 SOPA    FUSION | Planet Rescue | Whistleblower Protection | Innova… minor_or…
53 HMP     Legalise Cannabis Party                                     minor_or…
54 GRPF    Gerard Rennick People First                                 minor_or…
55 GRN     The Greens (WA) Inc                                         minor_or…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate national first preference vote percentages</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>first_prefs <span class="ot">&lt;-</span> data_classified <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(CountNumber <span class="sc">==</span> <span class="dv">0</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>         CalculationType <span class="sc">==</span> <span class="st">"Preference Count"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate total votes per party type per year</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>vote_shares <span class="ot">&lt;-</span> first_prefs <span class="sc">|&gt;</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, PartyType) <span class="sc">|&gt;</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_votes =</span> <span class="fu">sum</span>(CalculationValue, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> total_votes <span class="sc">/</span> <span class="fu">sum</span>(total_votes) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># View results</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>vote_shares</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
   year PartyType      total_votes   pct
  &lt;dbl&gt; &lt;chr&gt;                &lt;dbl&gt; &lt;dbl&gt;
1  2022 major_coal         5233334  35.7
2  2022 major_labour       4776030  32.6
3  2022 minor_or_indep     4649678  31.7
4  2025 major_coal         4929402  31.8
5  2025 major_labour       5354138  34.6
6  2025 minor_or_indep     5206696  33.6</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save processed data</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(data_classified, <span class="st">"data/data_classified.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="spatial-analysis" class="level1">
<h1><strong>Spatial analysis</strong></h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate vote share per electorate per year</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>electorate_votes <span class="ot">&lt;-</span> first_prefs <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year, DivisionNm, PartyType) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_votes =</span> <span class="fu">sum</span>(CalculationValue, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct =</span> total_votes <span class="sc">/</span> <span class="fu">sum</span>(total_votes) <span class="sc">*</span> <span class="dv">100</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>electorate_votes</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 903 × 5
    year DivisionNm PartyType      total_votes   pct
   &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;                &lt;dbl&gt; &lt;dbl&gt;
 1  2022 Adelaide   major_coal           36080  32.0
 2  2022 Adelaide   major_labour         45086  40.0
 3  2022 Adelaide   minor_or_indep       31598  28.0
 4  2022 Aston      major_coal           42260  43.1
 5  2022 Aston      major_labour         31949  32.5
 6  2022 Aston      minor_or_indep       23951  24.4
 7  2022 Ballarat   major_coal           26142  27.1
 8  2022 Ballarat   major_labour         43171  44.7
 9  2022 Ballarat   minor_or_indep       27187  28.2
10  2022 Banks      major_coal           41622  45.2
# ℹ 893 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage point change between 2022 and 2025</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>electorate_change <span class="ot">&lt;-</span> electorate_votes <span class="sc">|&gt;</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(year, DivisionNm, PartyType, pct) <span class="sc">|&gt;</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> year, <span class="at">values_from =</span> pct, <span class="at">names_prefix =</span> <span class="st">"pct_"</span>) <span class="sc">|&gt;</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">pct_change =</span> pct_2025 <span class="sc">-</span> pct_2022,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">trend_dir =</span> <span class="fu">case_when</span>(</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>      pct_change <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"increase"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>      pct_change <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">~</span> <span class="st">"decrease"</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"no_change"</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Save processed data</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="fu">write_csv</span>(electorate_change, <span class="st">"data/electorate_change.csv"</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>electorate_change</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 456 × 6
   DivisionNm PartyType      pct_2022 pct_2025 pct_change trend_dir
   &lt;chr&gt;      &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    
 1 Adelaide   major_coal         32.0     24.2     -7.83  decrease 
 2 Adelaide   major_labour       40.0     46.5      6.50  increase 
 3 Adelaide   minor_or_indep     28.0     29.3      1.33  increase 
 4 Aston      major_coal         43.1     37.7     -5.38  decrease 
 5 Aston      major_labour       32.5     37.3      4.71  increase 
 6 Aston      minor_or_indep     24.4     25.1      0.672 increase 
 7 Ballarat   major_coal         27.1     28.6      1.50  increase 
 8 Ballarat   major_labour       44.7     42.4     -2.39  decrease 
 9 Ballarat   minor_or_indep     28.2     29.1      0.891 increase 
10 Banks      major_coal         45.2     39.1     -6.12  decrease 
# ℹ 446 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>demographic <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"data/demographic-classification-as-at-4-march-2025.csv"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">skip =</span> <span class="dv">3</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>) <span class="sc">|&gt;</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">DivisionNm =</span> <span class="dv">1</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">DemographicClass =</span> <span class="dv">2</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">State =</span> <span class="dv">3</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Join demographic classifications to electorate change data</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>electorate_change_demo <span class="ot">&lt;-</span> electorate_change <span class="sc">|&gt;</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(demographic, <span class="at">by =</span> <span class="st">"DivisionNm"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarise average pct_change by demographic class and party type</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>demo_summary <span class="ot">&lt;-</span> electorate_change_demo <span class="sc">|&gt;</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(DemographicClass)) <span class="sc">|&gt;</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DemographicClass, PartyType) <span class="sc">|&gt;</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_pct_change =</span> <span class="fu">mean</span>(pct_change, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>demo_summary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 3
   DemographicClass   PartyType      avg_pct_change
   &lt;chr&gt;              &lt;chr&gt;                   &lt;dbl&gt;
 1 Inner Metropolitan major_coal              -3.32
 2 Inner Metropolitan major_labour             2.28
 3 Inner Metropolitan minor_or_indep           1.04
 4 Outer Metropolitan major_coal              -4.72
 5 Outer Metropolitan major_labour             2.69
 6 Outer Metropolitan minor_or_indep           2.03
 7 Provincial         major_coal              -2.56
 8 Provincial         major_labour             1.42
 9 Provincial         minor_or_indep           1.14
10 Rural              major_coal              -4.41
11 Rural              major_labour             1.26
12 Rural              minor_or_indep           3.15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar chart visualisation for demographic summary</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(demo_summary, <span class="fu">aes</span>(<span class="at">x =</span> DemographicClass, <span class="at">y =</span> avg_pct_change, <span class="at">fill =</span> PartyType)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"major_coal"</span> <span class="ot">=</span> <span class="st">"#0047AB"</span>,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"major_labour"</span> <span class="ot">=</span> <span class="st">"#DE3533"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"minor_or_indep"</span> <span class="ot">=</span> <span class="st">"#10C25B"</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average change in first preference votes by demographic classification"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Demographic Classification"</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Average % point change"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"Party Type"</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="demographic-deep-dive" class="level1">
<h1><strong>Demographic deep dive</strong></h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Selecting an Electorate with Significant Voting Shift</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Exploratory analysis</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>electorate_change <span class="sc">|&gt;</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PartyType <span class="sc">==</span> <span class="st">"minor_or_indep"</span>) <span class="sc">|&gt;</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_change)) <span class="sc">|&gt;</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 152 × 6
   DivisionNm PartyType      pct_2022 pct_2025 pct_change trend_dir
   &lt;chr&gt;      &lt;chr&gt;             &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    
 1 Calare     minor_or_indep     37.2     59.9      22.7  increase 
 2 Calwell    minor_or_indep     31.5     53.8      22.3  increase 
 3 Blaxland   minor_or_indep     18.0     34.4      16.4  increase 
 4 Watson     minor_or_indep     21.6     36.8      15.2  increase 
 5 Paterson   minor_or_indep     22.6     35.7      13.1  increase 
 6 Farrer     minor_or_indep     28.8     41.5      12.7  increase 
 7 Forrest    minor_or_indep     29.4     41.5      12.0  increase 
 8 Monash     minor_or_indep     36.6     47.9      11.3  increase 
 9 Fremantle  minor_or_indep     31.8     42.5      10.7  increase 
10 Moore      minor_or_indep     25.4     36.0      10.6  increase 
11 Parkes     minor_or_indep     30.5     40.4       9.91 increase 
12 Wannon     minor_or_indep     36.4     45.8       9.36 increase 
13 Lyne       minor_or_indep     35.0     43.9       8.92 increase 
14 Burt       minor_or_indep     25.4     34.1       8.71 increase 
15 Riverina   minor_or_indep     33.0     41.2       8.29 increase 
16 Fisher     minor_or_indep     32.4     40.5       8.09 increase 
17 Flynn      minor_or_indep     29.6     37.5       7.93 increase 
18 Wills      minor_or_indep     43.8     51.5       7.71 increase 
19 Makin      minor_or_indep     22.3     29.7       7.43 increase 
20 Bean       minor_or_indep     28.6     35.9       7.36 increase 
# ℹ 132 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>electorate_change <span class="sc">|&gt;</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(PartyType <span class="sc">==</span> <span class="st">"major_coal"</span>) <span class="sc">|&gt;</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(pct_change) <span class="sc">|&gt;</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 152 × 6
   DivisionNm PartyType  pct_2022 pct_2025 pct_change trend_dir
   &lt;chr&gt;      &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    
 1 Calare     major_coal     47.7     29.7     -18.0  decrease 
 2 Braddon    major_coal     44.1     31.7     -12.4  decrease 
 3 Watson     major_coal     26.5     15.2     -11.4  decrease 
 4 Hasluck    major_coal     33.4     22.2     -11.2  decrease 
 5 Lyons      major_coal     37.2     26.2     -11.0  decrease 
 6 Moore      major_coal     41.8     31.4     -10.4  decrease 
 7 Hindmarsh  major_coal     32.7     23.1      -9.59 decrease 
 8 Robertson  major_coal     40.0     30.4      -9.58 decrease 
 9 Paterson   major_coal     36.7     27.2      -9.45 decrease 
10 Leichhardt major_coal     36.7     27.3      -9.44 decrease 
11 Parkes     major_coal     49.3     40.0      -9.36 decrease 
12 Bonner     major_coal     44.8     35.5      -9.34 decrease 
13 Rankin     major_coal     29.0     19.7      -9.26 decrease 
14 Hunter     major_coal     27.4     18.2      -9.25 decrease 
15 Wright     major_coal     43.2     34.1      -9.13 decrease 
16 Makin      major_coal     31.4     22.5      -8.95 decrease 
17 Farrer     major_coal     52.3     43.4      -8.85 decrease 
18 Sturt      major_coal     43.1     34.3      -8.80 decrease 
19 Bass       major_coal     39.7     31.4      -8.29 decrease 
20 Calwell    major_coal     23.7     15.7      -7.96 decrease 
# ℹ 132 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>electorate_change <span class="sc">|&gt;</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DivisionNm <span class="sc">==</span> <span class="st">"Monash"</span>, PartyType <span class="sc">==</span> <span class="st">"major_coal"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  DivisionNm PartyType  pct_2022 pct_2025 pct_change trend_dir
  &lt;chr&gt;      &lt;chr&gt;         &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;    
1 Monash     major_coal     37.8     31.8      -6.01 decrease </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>census_g02 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G02_VIC_SA1.csv"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(census_g02)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 15,482
Columns: 9
$ SA1_CODE_2021                 &lt;dbl&gt; 20101100101, 20101100102, 20101100105, 2…
$ Median_age_persons            &lt;dbl&gt; 39, 49, 33, 40, 46, 35, 39, 45, 40, 47, …
$ Median_mortgage_repay_monthly &lt;dbl&gt; 1452, 1257, 1136, 1302, 1044, 1517, 1300…
$ Median_tot_prsnl_inc_weekly   &lt;dbl&gt; 713, 629, 552, 642, 623, 840, 733, 857, …
$ Median_rent_weekly            &lt;dbl&gt; 330, 235, 279, 330, 280, 355, 280, 400, …
$ Median_tot_fam_inc_weekly     &lt;dbl&gt; 1852, 2050, 1266, 1562, 1212, 2111, 1483…
$ Average_num_psns_per_bedroom  &lt;dbl&gt; 0.8, 0.7, 0.8, 0.7, 0.7, 0.8, 0.7, 0.8, …
$ Median_tot_hhd_inc_weekly     &lt;dbl&gt; 1224, 1281, 954, 1271, 891, 1858, 1184, …
$ Average_household_size        &lt;dbl&gt; 2.6, 2.4, 2.0, 2.5, 1.8, 2.7, 2.2, 3.1, …</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Analyse spatial distribution of demographic characteristics</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the maps</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>aec_map <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"data/vic-july-2021-esri/E_VIC21_region.shp"</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Elect_div =</span> <span class="fu">toupper</span>(Elect_div))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02 <span class="ot">&lt;-</span> <span class="fu">read_sf</span>(<span class="st">"data/Geopackage_2021_G02_VIC_GDA2020/G02_VIC_GDA2020.gpkg"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>                           <span class="at">layer =</span> <span class="st">"G02_SA1_2021_VIC"</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Transform projection</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>aec_map<span class="sc">$</span>geometry <span class="ot">=</span> <span class="fu">st_transform</span>(aec_map<span class="sc">$</span>geometry, <span class="dv">7844</span>)</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Get SA1 centroids</span></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02_w_centroid <span class="ot">&lt;-</span> vicmap_sa1_G02 <span class="sc">|&gt;</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">centroid =</span> <span class="fu">st_centroid</span>(geom))</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Find which electorate each SA1 belongs to</span></span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a>electoral_intersects <span class="ot">=</span> <span class="fu">st_intersects</span>(vicmap_sa1_G02_w_centroid<span class="sc">$</span>centroid, </span>
<span id="cb25-20"><a href="#cb25-20" aria-hidden="true" tabindex="-1"></a>                                     aec_map<span class="sc">$</span>geometry, </span>
<span id="cb25-21"><a href="#cb25-21" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">sparse =</span> <span class="cn">FALSE</span>)</span>
<span id="cb25-22"><a href="#cb25-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-23"><a href="#cb25-23" aria-hidden="true" tabindex="-1"></a>arr_ind <span class="ot">=</span> <span class="fu">which</span>(electoral_intersects <span class="sc">==</span> <span class="cn">TRUE</span>, <span class="at">arr.ind =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-24"><a href="#cb25-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-25"><a href="#cb25-25" aria-hidden="true" tabindex="-1"></a>sa1_ind <span class="ot">=</span> arr_ind[,<span class="dv">1</span>]</span>
<span id="cb25-26"><a href="#cb25-26" aria-hidden="true" tabindex="-1"></a>division_ind <span class="ot">=</span> arr_ind[,<span class="dv">2</span>]</span>
<span id="cb25-27"><a href="#cb25-27" aria-hidden="true" tabindex="-1"></a>division_name <span class="ot">=</span> aec_map<span class="sc">$</span>Elect_div[division_ind]</span>
<span id="cb25-28"><a href="#cb25-28" aria-hidden="true" tabindex="-1"></a>sa1_name <span class="ot">=</span> vicmap_sa1_G02_w_centroid<span class="sc">$</span>SA1_NAME_2021[sa1_ind]</span>
<span id="cb25-29"><a href="#cb25-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-30"><a href="#cb25-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Save SA1 to electorate mapping</span></span>
<span id="cb25-31"><a href="#cb25-31" aria-hidden="true" tabindex="-1"></a>sa1_divisions <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">SA1_NAME_2021 =</span> sa1_name,</span>
<span id="cb25-32"><a href="#cb25-32" aria-hidden="true" tabindex="-1"></a>                           <span class="at">DivisionNm =</span> division_name)</span>
<span id="cb25-33"><a href="#cb25-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-34"><a href="#cb25-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Add electorate names to census data</span></span>
<span id="cb25-35"><a href="#cb25-35" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02_electorates <span class="ot">&lt;-</span> vicmap_sa1_G02 <span class="sc">|&gt;</span></span>
<span id="cb25-36"><a href="#cb25-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(sa1_divisions)</span>
<span id="cb25-37"><a href="#cb25-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-38"><a href="#cb25-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by electorate and calculate averages</span></span>
<span id="cb25-39"><a href="#cb25-39" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02_electorates_grouped <span class="ot">&lt;-</span> vicmap_sa1_G02_electorates <span class="sc">|&gt;</span></span>
<span id="cb25-40"><a href="#cb25-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(DivisionNm) <span class="sc">|&gt;</span></span>
<span id="cb25-41"><a href="#cb25-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-42"><a href="#cb25-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_fam_income =</span> <span class="fu">mean</span>(Median_tot_fam_inc_weekly, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-43"><a href="#cb25-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_mortgage =</span> <span class="fu">mean</span>(Median_mortgage_repay_monthly, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb25-44"><a href="#cb25-44" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb25-45"><a href="#cb25-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb25-46"><a href="#cb25-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-47"><a href="#cb25-47" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(vicmap_sa1_G02_electorates_grouped)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 3 fields
Geometry type: POLYGON
Dimension:     XY
Bounding box:  xmin: 143.4406 ymin: -38.0745 xmax: 146.1925 ymax: -36.37084
Geodetic CRS:  GDA2020
# A tibble: 6 × 4
  DivisionNm mean_fam_income mean_mortgage                                  geom
  &lt;chr&gt;                &lt;dbl&gt;         &lt;dbl&gt;                         &lt;POLYGON [°]&gt;
1 ASTON                2164.         1953. ((145.2593 -37.83661, 145.2591 -37.8…
2 BALLARAT             1862.         1460. ((143.6553 -37.60974, 143.6545 -37.6…
3 BENDIGO              1814.         1423. ((144.518 -36.72529, 144.5181 -36.72…
4 BRUCE                1840.         1755. ((145.2192 -37.94013, 145.2191 -37.9…
5 CALWELL              1732.         1693. ((144.8676 -37.67103, 144.8676 -37.6…
6 CASEY                2181.         1925. ((145.3088 -37.79399, 145.3088 -37.7…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a separate dataset for Monash only</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>monash_only <span class="ot">&lt;-</span> vicmap_sa1_G02_electorates_grouped <span class="sc">|&gt;</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(DivisionNm <span class="sc">==</span> <span class="st">"MONASH"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 1 - median family income by electorate</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vicmap_sa1_G02_electorates_grouped) <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">geometry =</span> geom, <span class="at">fill =</span> mean_fam_income)) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> monash_only, <span class="fu">aes</span>(<span class="at">geometry =</span> geom), </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"darkgreen"</span>) <span class="sc">+</span></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average median family income by electorate"</span>,</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Victoria, 2021 Census. Monash highlighted in red."</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Avg median family</span><span class="sc">\n</span><span class="st">income (weekly $)"</span>) <span class="sc">+</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot 2 - median mortgage repayment by electorate</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(vicmap_sa1_G02_electorates_grouped) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">geometry =</span> geom, <span class="at">fill =</span> mean_mortgage)) <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> monash_only, <span class="fu">aes</span>(<span class="at">geometry =</span> geom), </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average median mortgage repayment by electorate"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Victoria, 2021 Census. Monash highlighted in red."</span>,</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Avg median mortgage</span><span class="sc">\n</span><span class="st">(monthly $)"</span>) <span class="sc">+</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Quality checks on spatial join</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="co"># How many SA1s didn't match any electorate?</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(vicmap_sa1_G02) <span class="sc">-</span> <span class="fu">nrow</span>(vicmap_sa1_G02_electorates)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Any missing values in our key variables?</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02_electorates_grouped <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_income =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(mean_fam_income)),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">missing_mortgage =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(mean_mortgage))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 1 feature and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 140.9619 ymin: -39.15918 xmax: 149.9762 ymax: -33.98064
Geodetic CRS:  GDA2020
# A tibble: 1 × 3
  missing_income missing_mortgage                                           geom
           &lt;int&gt;            &lt;int&gt;                             &lt;MULTIPOLYGON [°]&gt;
1              0                0 (((144.6863 -38.24588, 144.6869 -38.24571, 14…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare Monash vs Rest of VIC for census variables</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>vicmap_sa1_G02_electorates_grouped <span class="sc">|&gt;</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">is_monash =</span> <span class="fu">ifelse</span>(DivisionNm <span class="sc">==</span> <span class="st">"MONASH"</span>, <span class="st">"Monash"</span>, <span class="st">"Rest of VIC"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(is_monash) <span class="sc">|&gt;</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_fam_income =</span> <span class="fu">mean</span>(mean_fam_income, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">avg_mortgage =</span> <span class="fu">mean</span>(mean_mortgage, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 2 features and 3 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 140.9619 ymin: -39.15918 xmax: 149.9762 ymax: -33.98064
Geodetic CRS:  GDA2020
# A tibble: 2 × 4
  is_monash   avg_fam_income avg_mortgage                                   geom
  &lt;chr&gt;                &lt;dbl&gt;        &lt;dbl&gt;                     &lt;MULTIPOLYGON [°]&gt;
1 Monash               1660.        1470. (((145.2893 -38.45516, 145.2896 -38.4…
2 Rest of VIC          2184.        1908. (((146.1919 -37.58752, 146.1923 -37.5…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Explore demographic profile of selected electorate</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Load libraries</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>g01 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G01_VIC_SA1.csv"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">SA1_CODE_2021 =</span> <span class="fu">as.character</span>(SA1_CODE_2021)) <span class="sc">|&gt;</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(sa1_divisions, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"SA1_CODE_2021"</span> <span class="ot">=</span> <span class="st">"SA1_NAME_2021"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">ifelse</span>(DivisionNm <span class="sc">==</span> <span class="st">"MONASH"</span>, <span class="st">"Monash"</span>, <span class="st">"Rest of VIC"</span>))</span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a>g17a <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/2021Census_G17A_VIC_SA1.csv"</span>)</span>
<span id="cb35-14"><a href="#cb35-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-15"><a href="#cb35-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-16"><a href="#cb35-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy Age and Gender data</span></span>
<span id="cb35-17"><a href="#cb35-17" aria-hidden="true" tabindex="-1"></a>g01_long <span class="ot">&lt;-</span> g01 <span class="sc">|&gt;</span></span>
<span id="cb35-18"><a href="#cb35-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(SA1_CODE_2021, region, </span>
<span id="cb35-19"><a href="#cb35-19" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_0_4"</span>), <span class="fu">starts_with</span>(<span class="st">"Age_5_14"</span>),</span>
<span id="cb35-20"><a href="#cb35-20" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_15_19"</span>), <span class="fu">starts_with</span>(<span class="st">"Age_20_24"</span>),</span>
<span id="cb35-21"><a href="#cb35-21" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_25_34"</span>), <span class="fu">starts_with</span>(<span class="st">"Age_35_44"</span>),</span>
<span id="cb35-22"><a href="#cb35-22" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_45_54"</span>), <span class="fu">starts_with</span>(<span class="st">"Age_55_64"</span>),</span>
<span id="cb35-23"><a href="#cb35-23" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_65_74"</span>), <span class="fu">starts_with</span>(<span class="st">"Age_75_84"</span>),</span>
<span id="cb35-24"><a href="#cb35-24" aria-hidden="true" tabindex="-1"></a>         <span class="fu">starts_with</span>(<span class="st">"Age_85ov"</span>),</span>
<span id="cb35-25"><a href="#cb35-25" aria-hidden="true" tabindex="-1"></a>         <span class="sc">-</span><span class="fu">ends_with</span>(<span class="st">"_P"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-26"><a href="#cb35-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="fu">c</span>(SA1_CODE_2021, region),</span>
<span id="cb35-27"><a href="#cb35-27" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"category"</span>,</span>
<span id="cb35-28"><a href="#cb35-28" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-29"><a href="#cb35-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb35-30"><a href="#cb35-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">sex =</span> <span class="fu">str_extract</span>(category, <span class="st">"[MF]$"</span>),</span>
<span id="cb35-31"><a href="#cb35-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">age =</span> <span class="fu">str_remove</span>(category, <span class="st">"_[MF]$"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-32"><a href="#cb35-32" aria-hidden="true" tabindex="-1"></a>          <span class="fu">str_remove</span>(<span class="st">"Age_"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-33"><a href="#cb35-33" aria-hidden="true" tabindex="-1"></a>          <span class="fu">str_remove</span>(<span class="st">"_yr"</span>)</span>
<span id="cb35-34"><a href="#cb35-34" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb35-35"><a href="#cb35-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-36"><a href="#cb35-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-37"><a href="#cb35-37" aria-hidden="true" tabindex="-1"></a><span class="co"># PLOT 1 - AGE DISTRIBUTION</span></span>
<span id="cb35-38"><a href="#cb35-38" aria-hidden="true" tabindex="-1"></a>g01_long <span class="sc">|&gt;</span></span>
<span id="cb35-39"><a href="#cb35-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(region <span class="sc">==</span> <span class="st">"Monash"</span>) <span class="sc">|&gt;</span></span>
<span id="cb35-40"><a href="#cb35-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age) <span class="sc">|&gt;</span></span>
<span id="cb35-41"><a href="#cb35-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-42"><a href="#cb35-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb35-43"><a href="#cb35-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age =</span> <span class="fu">fct_relevel</span>(age, <span class="st">"0_4"</span>, <span class="st">"5_14"</span>, <span class="st">"15_19"</span>, <span class="st">"20_24"</span>, </span>
<span id="cb35-44"><a href="#cb35-44" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"25_34"</span>, <span class="st">"35_44"</span>, <span class="st">"45_54"</span>, <span class="st">"55_64"</span>, </span>
<span id="cb35-45"><a href="#cb35-45" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"65_74"</span>, <span class="st">"75_84"</span>, <span class="st">"85ov"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-46"><a href="#cb35-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> total)) <span class="sc">+</span></span>
<span id="cb35-47"><a href="#cb35-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steel blue"</span>) <span class="sc">+</span></span>
<span id="cb35-48"><a href="#cb35-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Age distribution in Monash"</span>,</span>
<span id="cb35-49"><a href="#cb35-49" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"2021 Census"</span>,</span>
<span id="cb35-50"><a href="#cb35-50" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age group"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb35-51"><a href="#cb35-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb35-52"><a href="#cb35-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># PLOT 2 - GENDER DISTRIBUTION</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>g01 <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(region <span class="sc">==</span> <span class="st">"Monash"</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Male =</span> <span class="fu">sum</span>(Tot_P_M, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Female =</span> <span class="fu">sum</span>(Tot_P_F, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">everything</span>(),</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"gender"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> count, <span class="at">fill =</span> gender)) <span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>() <span class="sc">+</span></span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gender distribution in Monash"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"2021 Census"</span>,</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Gender"</span>, <span class="at">y =</span> <span class="st">"Count"</span>, <span class="at">fill =</span> <span class="st">"Gender"</span>) <span class="sc">+</span></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy income data</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>g17_long <span class="ot">&lt;-</span> g17a <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span><span class="dv">1</span>, <span class="at">names_to =</span> <span class="st">"category"</span>, <span class="at">values_to =</span> <span class="st">"count"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">str_detect</span>(category, <span class="st">"Tot"</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>         <span class="sc">!</span><span class="fu">str_detect</span>(category, <span class="st">"PI_NS"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"Neg_Nil_income"</span>, <span class="st">"-Inf_0"</span>),</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"Neg_Nil_incme"</span>, <span class="st">"-Inf_0"</span>),</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"Negtve_Nil_incme"</span>, <span class="st">"-Inf_0"</span>),</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"more"</span>, <span class="st">"Inf"</span>),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"85ov"</span>, <span class="st">"85_110_yrs"</span>),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">category =</span> <span class="fu">str_replace</span>(category, <span class="st">"85_yrs_ovr"</span>, <span class="st">"85_110_yrs"</span>)</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate_wider_delim</span>(category, <span class="at">delim =</span> <span class="st">"_"</span>,</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>                       <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"income_min"</span>, <span class="st">"income_max"</span>, <span class="st">"age_min"</span>, <span class="st">"age_max"</span>, <span class="st">"extra"</span>),</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>                       <span class="at">too_many =</span> <span class="st">"drop"</span>,</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>                       <span class="at">too_few =</span> <span class="st">"align_start"</span>) <span class="sc">|&gt;</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">income_bracket =</span> <span class="fu">paste</span>(income_min, income_max, <span class="at">sep =</span> <span class="st">"_"</span>),</span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">SA1_CODE_2021 =</span> <span class="fu">as.character</span>(SA1_CODE_2021)</span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb37-22"><a href="#cb37-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(sa1_divisions, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"SA1_CODE_2021"</span> <span class="ot">=</span> <span class="st">"SA1_NAME_2021"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb37-23"><a href="#cb37-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">region =</span> <span class="fu">ifelse</span>(DivisionNm <span class="sc">==</span> <span class="st">"MONASH"</span>, <span class="st">"Monash"</span>, <span class="st">"Rest of VIC"</span>))</span>
<span id="cb37-24"><a href="#cb37-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-25"><a href="#cb37-25" aria-hidden="true" tabindex="-1"></a><span class="co"># PLOT 3 - INCOME DISTRIBUTION</span></span>
<span id="cb37-26"><a href="#cb37-26" aria-hidden="true" tabindex="-1"></a>g17_long <span class="sc">|&gt;</span></span>
<span id="cb37-27"><a href="#cb37-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(region <span class="sc">==</span> <span class="st">"Monash"</span>,</span>
<span id="cb37-28"><a href="#cb37-28" aria-hidden="true" tabindex="-1"></a>         sex <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"M"</span>, <span class="st">"F"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb37-29"><a href="#cb37-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(income_bracket, income_min) <span class="sc">|&gt;</span></span>
<span id="cb37-30"><a href="#cb37-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total =</span> <span class="fu">sum</span>(count, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb37-31"><a href="#cb37-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb37-32"><a href="#cb37-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">income_min =</span> <span class="fu">as.numeric</span>(income_min),</span>
<span id="cb37-33"><a href="#cb37-33" aria-hidden="true" tabindex="-1"></a>         <span class="at">income_bracket =</span> <span class="fu">fct_reorder</span>(income_bracket, income_min)) <span class="sc">|&gt;</span></span>
<span id="cb37-34"><a href="#cb37-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> income_bracket, <span class="at">y =</span> total)) <span class="sc">+</span></span>
<span id="cb37-35"><a href="#cb37-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steel blue"</span>) <span class="sc">+</span></span>
<span id="cb37-36"><a href="#cb37-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Income distribution in Monash"</span>,</span>
<span id="cb37-37"><a href="#cb37-37" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"2021 Census"</span>,</span>
<span id="cb37-38"><a href="#cb37-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Income bracket (weekly $)"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb37-39"><a href="#cb37-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb37-40"><a href="#cb37-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="australian_election_analysis_files/figure-html/unnamed-chunk-8-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="key-findings" class="level1">
<h1><strong>Key Findings</strong></h1>
<section id="fact-checker-method-and-results" class="level3">
<h3 class="anchored" data-anchor-id="fact-checker-method-and-results"><strong>Fact Checker method and results</strong></h3>
</section>
<section id="method" class="level3">
<h3 class="anchored" data-anchor-id="method">Method:</h3>
<p>To fact-check the claim made by the Australia Institute, I gathered the distribution of the first preference votes by candidates and divisions for the 2022 and 2025 federal elections. I put these two sets of data together into a single dataframe along with a new year variable indicating which year an entry belongs to. Afterwards, I created a party category which then classified each party into one of three groups using case_when() in R:</p>
<ul>
<li><p>major_labour – Australian Labor Party (ALP)</p></li>
<li><p>major_coal – Liberal Party (LP), National Party (NP), Liberal National Party (LNP), and Country Liberal Party (CLP)</p></li>
<li><p>minor_or_indep – any other parties and independents (including Greens and One Nation)</p></li>
</ul>
<p>The calculation for the national vote share of the first preference was performed by filtering first preference votes (CountNumber == 0 &amp; CalculationType == “Preference Count”) and summing up the votes by PartyType within years to compute the proportion.</p>
<p>The AEC election data is publicly available and free to use under the Commonwealth of Australia copyright. The ABS Census data is similarly available under Creative Commons Attribution 4.0 International licence (CC BY 4.0).</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results:</h3>
<p>My estimated Coalition first preference vote for 2025 was 31.8% which is almost similar but not fully equal to the 32% obtained by the Australia Institute’s report. The difference could be because of rounding, which was done in the article. It is clear that the claim made by the Australia Institute is correct. In 2025, the minor parties and independents have more first preference votes compared to the coalition for the first time in history; this translates to 33.6% compared to 31.8%. This is an unprecedented change considering that in 2022, the minor parties and independents had 31.7% while the coalition had 35.7%.</p>
</section>
<section id="spatial-analysis-method-and-results" class="level3">
<h3 class="anchored" data-anchor-id="spatial-analysis-method-and-results"><strong>Spatial Analysis method and results</strong></h3>
</section>
<section id="method-1" class="level3">
<h3 class="anchored" data-anchor-id="method-1">Method</h3>
<p>To see whether there was a consistency in the pattern observed at the national level spatially, the change in vote share at the electorate level was compared against the demographic classification of the AEC (as at 4 March 2025). Each electorate is classified according to one of the following categories: Inner Metropolitan, Outer Metropolitan, Provincial, and Rural.</p>
<p>The independent/minor party votes in some electorates could potentially be zero in either or both years since no independent/minor party candidate contested. Such electorates could be in Rural or Provincial electorates. This could result in overstating or understating the percentage points gained by major parties depending on whether there were no independent/minor parties in either of the two years.</p>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<p>The bar graph indicates the average percentage change in the share of first-preference votes between 2022 and 2025, for each demographic classification. As shown in the bar chart below, the national trend was seen in all four demographic classifications:</p>
<ul>
<li><p>The Coalition lost ground in all four classifications, but the biggest decline occurred in Outer Metropolitan seats (-4.7%), while the least decline occurred in Provincial seats (-2.6%)</p></li>
<li><p>Labor saw an increase in all four demographic classifications, but the largest gain came in Outer Metropolitan seats (+2.7%)</p></li>
<li><p>Minor parties and independents showed an increase in all four demographic classifications, with the biggest increase occurring in Rural seats (+3.1%)</p></li>
</ul>
<p>It can be concluded from these results that the national pattern is not specific to any type of electorate but rather represents a pattern in individual electorates.</p>
</section>
<section id="demographic-deep-dive-and-results" class="level3">
<h3 class="anchored" data-anchor-id="demographic-deep-dive-and-results"><strong>Demographic Deep Dive and Results</strong></h3>
<p>The electorate of Monash was chosen to be studied due to its strong swing towards independents and minor parties (+11.3%), along with an evident swing against the Coalition Party (-6.0%) within the time frame of 2022-2025. The electorate of Monash is located in Melbourne’s outer eastern suburbs.</p>
</section>
<section id="census-variables--" class="level3">
<h3 class="anchored" data-anchor-id="census-variables--">Census Variables -</h3>
<p>Two variables were selected from the 2021 ABS Census G02 dataset:</p>
<ul>
<li><p>Median weekly family income (<code>Median_tot_fam_inc_weekly</code>) - Historically wealthier communities supported the Coalition, making income an interesting variable to examine given the swing away from Coalition in electorates like Monash.</p></li>
<li><p>Median monthly mortgage repayment (<code>Median_mortgage_repay_monthly</code>) — Housing affordability was one of the key issues in the 2025 election. Monthly mortgage repayments include both the stress related to paying off a loan and the value of property owned, which makes this particular variable different from just income measures. Higher mortgage payments usually correspond to high property prices.</p></li>
</ul>
</section>
<section id="spatial-join-method--" class="level3">
<h3 class="anchored" data-anchor-id="spatial-join-method--">Spatial Join Method -</h3>
<p>Census SA1 data was spatially joined to AEC electoral boundaries using the centroid method, where SA1 centroids were intersected with electorate boundary polygons. The VIC 2021 AEC boundaries were reprojected from GDA1994 to GDA2020 (EPSG:7844) to match the census spatial data.</p>
</section>
<section id="quality-checks-and-limitations--" class="level3">
<h3 class="anchored" data-anchor-id="quality-checks-and-limitations--">Quality Checks and Limitations -</h3>
<ul>
<li><p>Nine SA1s could not be matched to any electorate, likely because their centroids fell on boundaries or in water areas. No missing values were found for either census variable after joining.</p></li>
<li><p>The census data is from 2021 while the electoral data is from 2025, a four year gap during which Monash’s demographic profile may have changed. The census should therefore be treated as an approximation of the 2025 voter demographic.</p></li>
<li><p>Aggregating SA1 level medians by taking the mean of medians is a methodological simplification that may slightly over or underestimate true electorate level values.</p></li>
</ul>
</section>
<section id="results--" class="level3">
<h3 class="anchored" data-anchor-id="results--">Results -</h3>
<p>Comparing Monash to the rest of Victoria:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Area</th>
<th>Avg median family income (weekly)</th>
<th>Avg median mortgage (monthly)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Monash</td>
<td>$1,660</td>
<td>$1,470</td>
</tr>
<tr class="even">
<td>Rest of VIC</td>
<td>$2,184</td>
<td>$1,908</td>
</tr>
</tbody>
</table>
<p>Surprisingly, Monash scores even below the state average for both of these indicators, especially relative to inner Melbourne seats, indicating that it is not a typical high-income or high-mortgage electorate.</p>
<p>The demographic plots reveal the following about Monash’s voter profile:</p>
<ul>
<li><p>Age — The age distribution in Monash shows a notably older profile, with the largest groups being 55-64 and 65-74 year olds. Younger age groups (20-34) are underrepresented compared to older cohorts.</p></li>
<li><p>Gender — The gender distribution in Monash electorate reflects a fairly even ratio between males and females in Monash – similar to the state norm.</p></li>
<li><p>Income — The income distribution in Monash is concentrated within the lower-middle income levels and very few people belong to the higher income classes.</p></li>
</ul>
<p>Monash is broadly representative of Victoria in terms of gender distribution and age profile. But it falls below average with regard to family income levels and home mortgage payments as compared with other Victorian electorates. This makes the swing toward independents particularly interesting, driven not by wealthy inner-city Teal voters but by older, middle-income outer suburban residents.</p>
</section>
</section>
<section id="citations" class="level1">
<h1><strong>CITATIONS</strong></h1>
<p>Wickham H, Averick M, Bryan J, Chang W, McGowan LD, François R, Grolemund G, Hayes A, Henry L, Hester J, Kuhn M, Pedersen TL, Miller E, Bache SM, Müller K, Ooms J, Robinson D, Seidel DP, Spinu V, Takahashi K, Vaughan D, Wilke C, Woo K, Yutani H (2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, 4(43), 1686. doi:10.21105/joss.01686 <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a></p>
<p>Pebesma E, Bivand R (2023). <em>Spatial Data Science: With Applications in R</em>. Chapman and Hall/CRC. <a href="https://doi.org/10.1201/9780429459016" class="uri">https://doi.org/10.1201/9780429459016</a></p>
<p>Pebesma E (2018). “Simple Features for R: Standardized Support for Spatial Vector Data.” <em>The R Journal</em>, 10(1), 439-446. <a href="https://doi.org/10.32614/RJ-2018-009" class="uri">https://doi.org/10.32614/RJ-2018-009</a></p>
<p>Australian Electoral Commission (2025). <em>House of Representatives Distribution of Preferences by Candidate by Division</em>. <a href="https://results.aec.gov.au" class="uri">https://results.aec.gov.au</a></p>
<p>Australian Electoral Commission (2021). <em>Electoral Boundaries GIS Data</em>. <a href="https://www.aec.gov.au/electorates/gis/gis_datadownload.htm" class="uri">https://www.aec.gov.au/electorates/gis/gis_datadownload.htm</a></p>
<p>Australian Electoral Commission (2025). <em>Demographic Classification of Electoral Divisions</em>. <a href="https://www.aec.gov.au/electorates/maps.htm" class="uri">https://www.aec.gov.au/electorates/maps.htm</a></p>
<p>Australian Bureau of Statistics (2021). <em>2021 Census of Population and Housing: General Community Profile</em>. <a href="https://www.abs.gov.au/census" class="uri">https://www.abs.gov.au/census</a></p>
<p>The Australia Institute (2025). <em>2025 Federal Election: Minor Parties and Independents Outpoll Coalition</em>. <a href="https://australiainstitute.org.au" class="uri">https://australiainstitute.org.au</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>